# Site settings
title: Hafizh Fauzan
description: Hafizh Fauzan Resume

# User settings
username: Hafizh Fauzan
user_description: I\'m your average programmer, seeking for something new, neverending. No journey is too hard or too easy, it's all on you. Lately I have been immersed in the <b>Data Science Field</b>, Intern for Telkom Directorate Digital Business, an Indonesian Telecomunication Company that striving always to be the best.
user_title: Data Scientist Intern
email: hafizhfauzan24@gmail.com
# twitter_username: lorem_ipsum
github_username:  Fizdan
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
